version: "3"

services:
  app:
    container_name: api-whatsapp-node
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - 3010:3010
    volumes:
      - .:/usr/app
  
  redis:
    container_name: api-whatsapp-redis
    image: redis:alpine
    ports: 
      - 6380:6379

volumes:
  pgdata:
    driver: local
